version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
      - run:
          name: Install AWS cli
          command: |
                  sudo apt-get install python-dev python-pip
                  sudo pip install awscli
      - run:
          name: Configure AWS cli
          command: aws configure set default.s3.signature_version s3v4
      - run: 
          name: Add Cloudfront as Preview Service
          command: aws configure set preview.cloudfront true
      - run:
          name: Deploy to S3
          command: aws --region us-east-2 s3 sync ./ s3://scorekeeper.mnlhl.com/ --delete
    #   - run:
    #       name: Invalidate Cloudfront Cache
    #       command: aws cloudfront create-invalidation --distribution-id E2FAWMI755U6KQs --paths "/*"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          context: AWS
          requires:
            - build
          filters:
            branches:
              only:
                - master