version: 2
jobs:
  build:
    working_directory: ~/angular-cli-circleci
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Install AWS cli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: angular-build
          command: yarn ng build --prod --aot --no-progress
      - store_test_results:
          path: test-results.xml
      - store_artifacts:
          path: test-results.xml
          prefix: tests
  deploy:
    working_directory: ~/angular-cli-circleci
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Install AWS cli
          command: |
            sudo apt-get update
            sudo apt-get install awscli
            aws --version
      - run:
          name: angular-build
          command: yarn ng build --prod --aot --no-progress
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4
      - run:
          name: Deploy to S3
          command: aws --region us-east-2 s3 sync dist/broadcast s3://scorekeeper.mnlhl.com/ --delete
      - run:
          name: Add Cloudfront as Preview Service
          command: aws configure set preview.cloudfront true
      - run:
          name: Invalidate Cloudfront Cache
          command: aws cloudfront create-invalidation --distribution-id E4QJH2C7AE68H --paths "/*"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: AWS
          filters:
            branches:
              ignore:
                - master
      - deploy:
          context: AWS
          filters:
            branches:
              only:
                - master